# dummy mod
#install:
#  - sudo apt-get update 
#  - sudo apt-get install -y python3 
#  - sudo apt-get install -y  ocaml-native-compilers

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - ocaml-native-compilers
      - gcc-5
      - g++-5
 
script: 
  - mkdir bin
  - ln -s /usr/bin/gcc-5 bin/gcc
  - ln -s /usr/bin/g++-5 bin/g++
  - bin/gcc --version
  - bin/g++ --version
  - env PATH=bin:$PATH make "FBUILD_PARAMS=--build-cc=/usr/bin/gcc-5 --build-cxx=/usr/bin/g++-5 --build-c-flag=-std=c++11"

